theme: jekyll-theme-minimal
title: Kimberly Kao
description: A website that tracks my progress throughout college. 
logo: https://drive.google.com/file/d/1PJHHFWPepSJJjxiqO_pG5YmRlN0Z9TMK/view?usp=sharing
